### ISSUE TITLE
Switch from Sufia 7.3 gem to Hyrax 1.0

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#1189] opened 2017-03-03 15:34 UTC
### Descriptive summary

The switch is to get us on the baseline Hyrax path.  Hyrax 1.0 is the migration path for Sufia 7.3   

It will still involve some clean up of Namspaces, Application Overrides, and Configuration Details

### Expected behavior

Expected to be unnoticeable to our users.

**Comment by hortongn** [comment] 2017-05-05 17:55
Duplicate of #1287

**Closed by hortongn** 2017-05-05 17:55 UTC
Labels: Scholar 3.0
