### ISSUE TITLE
Google Scholar - identify scope of work

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#205] opened 2014-11-19 18:39 UTC
Determine scope of work to enable Google Scholar to index Scholar@UC.   Note that in the August 2014 release of Sufia work was added to support "Google Scholar-specific metadata embedding." -- this is one place to start looking (see http://projecthydra.org/2014/08/22/sufia-4-0-0-released/).  More information can also be found here: http://scholar.google.com/intl/en-US/scholar/inclusion.html#indexing.   I assume that our Metadata Working Group can also help us with this scope of work.

**Comment by hortongn** [comment] 2015-06-17 20:12
Duplicate of #336

**Closed by hortongn** 2015-06-17 20:12 UTC
Labels: question
