### ISSUE TITLE
Fix page responsiveness for mobile

### ISSUE THREAD

**Issue by 13miciunasl** [uclibs/scholar_uc#358] opened 2015-06-23 22:00 UTC
When viewing a work the page does not stretch across the entire screen, but rather stretches to fit the width of the "Files" container. The site actions bar wraps as though the page is fully stretched and out of space.
![screenshot_2015-06-23-17-57-48](https://cloud.githubusercontent.com/assets/9759017/8318335/a12a0076-19d1-11e5-8a8c-47f8d7ed82b7.png)

**Comment by hortongn** [comment] 2015-06-24 17:30
I can confirm this.  The "Files" section of a work (File, Filename, Date Uploaded, Visibility, Actions) is too wide for the screen.  It's not responsive.

**Comment by lawhorkl** [comment] 2016-02-05 14:15
It seems to be a rendering error with mobile chrome. I loaded it up in mobile firefox and the display is fine. I'd do more testing on other devices but I'm limited by the devices that I have.

**Comment by lawhorkl** [comment] 2016-02-11 17:31
Fixed by PR #17

**Closed** 2016-02-12 22:55 UTC
Labels: 3 - Done, bug
