### ISSUE TITLE
Embedded movie player and download link are not working on the FILE show page for a video file.

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc#1232] opened 2017-03-21 17:35 UTC
### Descriptive summary

The embedded movie player and download link are not working on the FILE show page for a video file.  (.avi, mp4, ...)  

### Expected behavior

It is expected that the embedded player work with the download link.

<img width="1214" alt="screen shot 2017-03-21 at 1 33 41 pm" src="https://cloud.githubusercontent.com/assets/5084562/24161605/49c7385c-0e3b-11e7-85c7-a35fc08f77aa.png">

**Comment by hortongn** [comment] 2017-05-12 01:35
Duplicate of #1346

**Closed by hortongn** 2017-05-12 01:35 UTC
Labels: Scholar 3.x
