### ISSUE TITLE
Removal of Sharing is incomplete

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc#1026] opened 2016-12-06 23:16 UTC
### Descriptive summary

As an owner/depositor, I can share a work with others and grant edit access.  If I remove this access, the removal is not taking place until the former editor edits the work one more time.

### Expected behavior
When I remove edit access from an individual work, the change should take place in a reasonable amount of time.  The former editor should not be able to edit the work one more time.

### Actual behavior
The former editor still has access to the work that they should no longer be able to edit, until they edit that work one more time (and until that last edit, with or without changes, is saved).  I have replicated this three times.

### Steps to reproduce the behavior

1. edit one of your works.  Go to the Share tab.  Under 'Share work with other users" search for a user, and then under 'Choose Access' select 'Edit.' Save the work.
1. As the other user (the editor) verify that you can edit the work.
1. As the submitter, remove the edit access.
1. As the other user (the former editor), verify that you can still edit the work until you edit the work one more time.

### Related testing
Probably wise to also test what happens, on a private or embargoed work, when View/Access is granted and then revoked. 

See also #1024.  Note that when Proxy access is revoked, the former proxy is left as an editor of works that they submitted.

**Comment by jamesvanmil** [comment] 2017-02-01 15:03
@newmanld Did you ever get any other errors when working though this? I'm seeing an LDP::Gone exception now when I'm working to recreate and test with workers running.

It looks like the permission is being deleted successfully in Fedora, but the application is still trying to access it (which produces the LDP::Gone) - an examination of the document in Solr shows that the edit permission is still recorded there, which explains why the editor still has access.

**Comment by newmanld** [comment] 2017-02-01 15:37
I don't recall seeing any error messages.  I was checking that edit access was appropriately revoked.

**Comment by hortongn** [comment] 2017-02-07 19:31
Confirmed the Ldp::Gone bug exists back in Sufia 7.2/Curation Concerns 1.6.3.  Going to to dig deeper to see if this is specific to Sufia or is in CC as well.  Will file a bug with the appropriate gem.

**Comment by hortongn** [comment] 2017-02-07 20:57
The Ldp::Gone error is a bug in hydra-head 10.4.0.  Pinning to 10.3.0 for now resolves it.

So that let's us continue work on the original bug removed above.

**Comment by jamesvanmil** [comment] 2017-02-09 19:14
Currently blocked by #1137

**Comment by hortongn** [comment] 2017-02-10 21:43
I'm still getting the Ldp::Gone error on Sufia 7.3.0.rc1 even with the newest active-fedora.  I'll confirm the error again and will then re-open the issue so the community knows.

**Comment by scherztc** [comment] 2017-03-03 18:33
Test issue on curly.libraries.uc.edu

**Comment by hortongn** [comment] 2017-03-06 22:25
Tested this again now that the LDP::Gone error has been resolves and I verified that this bug has also been resolved (in both Sufia and our app). So marking as closed.

**Closed by hortongn** 2017-03-06 22:25 UTC
Labels: Blocked, bug, Scholar 3.0

**Comment by scherztc** [comment] 2017-03-17 17:33
Size : 4
